name: CreeperStarBedwars
version: '1.9-SNAPSHOT'
main: cn.comicalpixel.creeperstarbedwars.CreeperStarBedwars
load: STARTUP
author: Xiaol789zxc

api-version: 1.8

softdepend: [ProtocolLib, My_Worlds, BKCommonLib, NameTagEdit, PlaceholderAPI]
folia-supported: false

commands:
  bw:
    description: CreeperStarBedwars Main Command.
  csbw:
    description: CreeperStarBedwars Main Command.
  cbw:
    description: CreeperStarBedwars Main Command.
  creeperstarbedwars:
    description: CreeperStarBedwars Main Command.
  comicalbedwars:
    description: CreeperStarBedwars Main Command.
  bedwars2025:
    description: CreeperStarBedwars Main Command.
  klpbw:
    description: CreeperStarBedwars Main Command.
  setup:
    description: CreeperStarBedwars game setup command.