name: CreeperStarBedwars
version: '1.0'
main: cn.comicalpixel.creeperstarbedwars.CreeperStarBedwars
load: STARTUP
author: Xiaol789zxc

softdepend: [ProtocolLib, My_Worlds, NameTagEdit, PlaceholderAPI]
folia-supported: false

commands:
  bw:
    description: CreeperStarBedwars Main Command.
  csbw:
    description: CreeperStarBedwars Main Command.
  cbw:
    description: CreeperStarBedwars Main Command.
  creeperstarbedwars:
    description: CreeperStarBedwars Main Command.
  setup:
    description: CreeperStarBedwars game setup command.